#!/usr/bin/env bash
rm -rf ./scripts/dist/local
rm -rf ./scripts/dist/remote
rm -rf ./scripts/dist/assets

mkdir -p ./scripts/generated_local
mkdir -p ./scripts/generated_remote
mkdir -p ./scripts/dist/local
mkdir -p ./scripts/dist/remote
mkdir -p ./scripts/dist/assets
mkdir -p ./generators/out

rm config.json
cp config/manual.json config.json
cp config/clients/$(cat ./config/client.json | jq .id | tr -d '"')/manual.json config.json

# Various autogenerated entries
for script in ./generators/types/*.py; do
    python "$script"
done

./dist/scanner/scanner

# Merge respective generator files
./dist/combine_partials/combine_partials
./dist/combine/combine

# Generate a init and cleanup script for the autogenerated scripts
# WIP: Will add once implemented
# python3 ./generators/server-scripts.py

mv ./scripts/generated_local/* ./scripts/dist/local
cp -r ./scripts/manual_local/* ./scripts/dist/local
mv ./scripts/generated_remote/* ./scripts/dist/remote
cp ./scripts/manual_remote/* ./scripts/dist/remote
cp -r ./scripts/assets/* ./scripts/dist/assets

rm -rf ./scripts/generated_local
rm -rf ./scripts/generated_remote
rm -rf ./generators/out

./generators/after.sh
